version: "3.8"
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=michal
      - MYSQL_DATABASE=mindfuldb
    ports:
      - 3306:3306
#    volumes:
#      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    image: mindful-home
    container_name: mindful-app
    restart: on-failure
    ports:
      - 8080:8080
##    environment:
##      SPRING_APPLICATION_JSON: '{
##        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
##        "spring.datasource.username" : "$MYSQLDB_USER",
##        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
##        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
##        "spring.jpa.hibernate.ddl-auto" : "update"
##      }'
##    volumes:
##      - .m2:/root/.m2
##    stdin_open: true
##    tty: true
#volumes:
#  db:
#
#
